Add tutorial as the second demo.
I created a new demo based on the "Feldera: The Basics" tutorial.  The
idea is that people who are too lazy to go through all the steps in the
tutorial can just play with the resulting pipeline.

- Added missing Python API to create URL input connectors.
- Added `project_demo06-SupplyChainTutorial` demo, which creates and
  configures the pipeline described in the tutorial using API with one
  differences: it doesn't set Kafka broker address in the connectors, so that the
    pipeline picks them up from the `REDPANDA_BROKERS` env variable.
    This way the demo works both in docker and locally.
- Modified `docker-compose.yml` to create the new demo, along with the
  SecOps demo in the demo profile.
  - In the process, added a dependency on the redpanda container to the
    demo, so it doesn't start until redpanda is up and running, and
    reduced the demo startup timeout from 5 to 1 seconds.  Perhaps even
    that is unnecessary.
- Updated the tutorial to point impatient users to the pre-made demo.

One issue with this is that we now compile two programs when running
with `--profile demo`, so it takes longer for the demo pipeline to become
available.  We could use a separate profile for the tutorial, but that's
going to become confusing and unwieldy.

Signed-off-by: Leonid Ryzhyk <leonid@feldera.com>

diff --git a/deploy/docker-compose.yml b/deploy/docker-compose.yml
--- a/deploy/docker-compose.yml
+++ b/deploy/docker-compose.yml
@@ -5,7 +5,7 @@ services:
     environment:
       POSTGRES_PASSWORD: postgres
     healthcheck:
-      test: ["CMD-SHELL", "pg_isready -U postgres"]
+      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
       interval: 10s
       timeout: 5s
       retries: 5
@@ -16,8 +16,8 @@ services:
     ports:
       - "8080:8080"
     depends_on:
-     db:
-       condition: service_healthy
+      db:
+        condition: service_healthy
     stop_grace_period: 0s
     environment:
       - RUST_BACKTRACE=1
@@ -30,14 +30,17 @@ services:
       - --use-auth=${USE_AUTH:-false}
     healthcheck:
       # TODO: add `/status` endpoint.
-      test: ["CMD-SHELL", "curl --fail --request GET --url http://localhost:8080/v0/pipelines"]
+      test:
+        [
+          "CMD-SHELL",
+          "curl --fail --request GET --url http://localhost:8080/v0/pipelines"
+        ]
       interval: 10s
       timeout: 5s
       retries: 5
 
-
   redpanda:
-    profiles: ["demo", "debezium"]
+    profiles: [ "demo", "debezium" ]
     command:
       - redpanda
       - start
@@ -70,16 +73,22 @@ services:
       - 19092:19092
       - 19644:9644
     healthcheck:
-      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
+      test:
+        [
+          "CMD-SHELL",
+          "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"
+        ]
       interval: 10s
       timeout: 3s
       retries: 5
       start_period: 5s
 
   demo:
-    profiles: ["demo"]
+    profiles: [ "demo" ]
     depends_on:
       pipeline-manager:
+        condition: service_healthy
+      redpanda:
         condition: service_healthy
     image: ghcr.io/feldera/demo-container:${FELDERA_VERSION:-0.1.6}
     environment:
@@ -87,8 +96,26 @@ services:
       - REDPANDA_BROKERS=redpanda:9092
       - SECOPS_DEMO_ARGS
       - RUST_LOG=info
+
+    # Run the demos after giving the service some time to initialize
+    # Start the two demos in parallel.  Compilation will still happen serially, but
+    # this way the user will see the two programs and pipelines straight away.
+    # Make sure the script returns an error if one of the demo scripts fails.
     command:
       - bash
       - -c
-      # Run the SecOps demo after giving the service some time to initialize
-      - "sleep 5 && cd demo/project_demo00-SecOps && python3 run.py --dbsp_url http://pipeline-manager:8080 --actions prepare create compile $${SECOPS_DEMO_ARGS}"
+      - |
+        sleep 1
+        (cd demo/project_demo00-SecOps && python3 run.py --dbsp_url http://pipeline-manager:8080 --actions prepare create compile $${SECOPS_DEMO_ARGS})&
+        pid1=$$!
+        echo pid1 $$pid1
+        (cd demo/project_demo06-SupplyChainTutorial && python3 run.py --dbsp_url http://pipeline-manager:8080 --actions prepare create compile)&
+        pid2=$$!
+        wait $$pid1
+        status1=$$?
+        echo SecOps demo script exited with status $$status1
+        wait $$pid2
+        status2=$$?
+        echo SupplyChainTutorial demo script exited with status $$status2
+        if [ $$status1 -ne 0 ]; then exit $$status1; fi
+        if [ $$status2 -ne 0 ]; then exit $$status2; fi
